# Assignment 1
## Data Collection & Preparation

API ที่เลือก :


Road crash locations เป็นข้อมูลเกี่ยวกับสถานที่และลักษณะของการขัดข้องภายในประเทศควีนส์แลนด์ สำหรับการจราจรบนถนนที่รายงานทั้งหมด 1 มกราคม 2544 ถึง 31 ธันวาคม 2561 

link API : https://www.data.qld.gov.au/dataset/crash-data-from-queensland-roads/resource/e88943c0-5968-4972-a15f-38e120d72ec0?truncate=30&inner_span=True

In [2]:
import urllib
import requests
from pandas.io.json import json_normalize
import json
import pandas as pd
import numpy as np
import requests

#Request API
url = 'https://www.data.qld.gov.au/api/3/action/datastore_search?resource_id=e88943c0-5968-4972-a15f-38e120d72ec0&limit=26000'
r = requests.get(url)
j = r.json()

In [3]:
#j

In [4]:
df = pd.DataFrame(j)
df = pd.DataFrame(j["result"]["records"])
df

,_id,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Hour,Crash_Nature,Crash_Type,Crash_Longitude_GDA94,...,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,1,Property damage only,2001,January,Monday,9,Angle,Multi-Vehicle,152.960485,...,0,0,0,2,0,0,0,0,0,0
1,2,2,Property damage only,2001,January,Tuesday,23,Hit object,Single Vehicle,153.038263,...,0,0,0,1,0,0,0,0,0,0
2,3,3,Medical treatment,2001,January,Tuesday,16,Angle,Multi-Vehicle,153.116342,...,1,0,1,2,0,0,0,0,0,0
3,4,4,Property damage only,2001,January,Tuesday,12,Rear-end,Multi-Vehicle,153.021629,...,0,0,0,2,0,0,0,0,0,0
4,5,5,Property damage only,2001,January,Tuesday,10,Rear-end,Multi-Vehicle,152.937497,...,0,0,0,3,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25995,25994,25994,Hospitalisation,2012,May,Monday,21,Hit object,Single Vehicle,152.096283,...,0,0,1,1,0,0,0,0,0,0
25996,25995,25995,Hospitalisation,2012,May,Monday,7,Angle,Multi-Vehicle,152.582484,...,0,0,1,1,1,0,0,0,0,0
25997,25996,25996,Hospitalisation,2012,May,Monday,14,Overturned,Single Vehicle,151.869054,...,0,0,1,1,0,0,0,0,0,0
25998,25997,25997,Medical treatment,2012,May,Monday,18,Hit object,Single Vehicle,151.029288,...,2,0,2,1,0,0,0,0,0,0
25999,25998,25998,Medical treatment,2012,May,Tuesday,13,Rear-end,Multi-Vehicle,153.128770,...,1,0,1,2,0,0,0,0,0,0

In [5]:
df.to_csv("Data/Road_Crash_location.csv")

In [6]:
df.shape

(26000, 53)

In [7]:
df.isnull().sum()

_id                                0
Crash_Ref_Number                   0
Crash_Severity                     0
Crash_Year                         0
Crash_Month                        0
Crash_Day_Of_Week                  0
Crash_Hour                         0
Crash_Nature                       0
Crash_Type                         0
Crash_Longitude_GDA94              0
Crash_Latitude_GDA94               0
Crash_Street                       0
Crash_Street_Intersecting          0
State_Road_Name                    0
Loc_Suburb                         0
Loc_Local_Government_Area          0
Loc_Post_Code                      0
Loc_Police_Division                0
Loc_Police_District                0
Loc_Police_Region                  0
Loc_Queensland_Transport_Region    0
Loc_Main_Roads_Region              0
Loc_ABS_Statistical_Area_2         0
Loc_ABS_Statistical_Area_3         0
Loc_ABS_Statistical_Area_4         0
Loc_ABS_Remoteness                 0
Loc_State_Electorate               0
Loc_Federal_Electorate             0
Crash_Controlling_Authority        0
Crash_Roadway_Feature              0
Crash_Traffic_Control              0
Crash_Speed_Limit                  0
Crash_Road_Surface_Condition       0
Crash_Atmospheric_Condition        0
Crash_Lighting_Condition           0
Crash_Road_Horiz_Align             0
Crash_Road_Vert_Align              0
Crash_DCA_Code                     8
Crash_DCA_Description              0
Crash_DCA_Group_Description        0
DCA_Key_Approach_Dir               0
Count_Casualty_Fatality            0
Count_Casualty_Hospitalised        0
Count_Casualty_MedicallyTreated    0
Count_Casualty_MinorInjury         0
Count_Casualty_Total               0
Count_Unit_Car                     0
Count_Unit_Motorcycle_Moped        0
Count_Unit_Truck                   0
Count_Unit_Bus                     0
Count_Unit_Bicycle                 0
Count_Unit_Pedestrian              0
Count_Unit_Other                   0
dtype: int64

In [8]:
df

,_id,Crash_Ref_Number,Crash_Severity,Crash_Year,Crash_Month,Crash_Day_Of_Week,Crash_Hour,Crash_Nature,Crash_Type,Crash_Longitude_GDA94,...,Count_Casualty_MedicallyTreated,Count_Casualty_MinorInjury,Count_Casualty_Total,Count_Unit_Car,Count_Unit_Motorcycle_Moped,Count_Unit_Truck,Count_Unit_Bus,Count_Unit_Bicycle,Count_Unit_Pedestrian,Count_Unit_Other
0,1,1,Property damage only,2001,January,Monday,9,Angle,Multi-Vehicle,152.960485,...,0,0,0,2,0,0,0,0,0,0
1,2,2,Property damage only,2001,January,Tuesday,23,Hit object,Single Vehicle,153.038263,...,0,0,0,1,0,0,0,0,0,0
2,3,3,Medical treatment,2001,January,Tuesday,16,Angle,Multi-Vehicle,153.116342,...,1,0,1,2,0,0,0,0,0,0
3,4,4,Property damage only,2001,January,Tuesday,12,Rear-end,Multi-Vehicle,153.021629,...,0,0,0,2,0,0,0,0,0,0
4,5,5,Property damage only,2001,January,Tuesday,10,Rear-end,Multi-Vehicle,152.937497,...,0,0,0,3,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25995,25994,25994,Hospitalisation,2012,May,Monday,21,Hit object,Single Vehicle,152.096283,...,0,0,1,1,0,0,0,0,0,0
25996,25995,25995,Hospitalisation,2012,May,Monday,7,Angle,Multi-Vehicle,152.582484,...,0,0,1,1,1,0,0,0,0,0
25997,25996,25996,Hospitalisation,2012,May,Monday,14,Overturned,Single Vehicle,151.869054,...,0,0,1,1,0,0,0,0,0,0
25998,25997,25997,Medical treatment,2012,May,Monday,18,Hit object,Single Vehicle,151.029288,...,2,0,2,1,0,0,0,0,0,0
25999,25998,25998,Medical treatment,2012,May,Tuesday,13,Rear-end,Multi-Vehicle,153.128770,...,1,0,1,2,0,0,0,0,0,0